version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    restart: always
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  shop:
    build: ./
    depends_on:
      - mongodb
    command: npm start
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - './:/app'

volumes:
  mongodb_data:
    driver: local
