version: '3.9'

services:
  database:
    image: mysql:8.0.12
    restart: always
    environment:
      MYSQL_DATABASE: node-online-shop
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - 'dbdata:/var/lib/mysql'
      - './database:/docker-entrypoint-initdb.d'

  shop:
    build: ./
    depends_on:
      - database
    command: npm start
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - './:/app'

volumes:
  dbdata:
    driver: local
